export const SEND_VERIFICATION_CODE = 'SEND_VERIFICATION_CODE'
export const SEND_VERIFICATION_CODE_SUCCESS = 'SEND_VERIFICATION_CODE_SUCCESS'
export const SEND_VERIFICATION_CODE_FAILURE = 'SEND_VERIFICATION_CODE_FAILURE'

export const VERIFY_CODE = 'VERIFY_CODE'
export const VERIFY_CODE_SUCCESS = 'VERIFY_CODE_SUCCESS'
export const VERIFY_CODE_FAILURE = 'VERIFY_CODE_FAILURE'

export const SETUP_PASSWORD = 'SETUP_PASSWORD'
export const SETUP_PASSWORD_SUCCESS = 'SETUP_PASSWORD_SUCCESS'
export const SETUP_PASSWORD_FAILURE = 'SETUP_PASSWORD_FAILURE'

export const START_PROCESS_AGAIN = 'START_PROCESS_AGAIN';