export const FETCH_ACTIVE_USER = 'FETCH_ACTIVE_USER'
export const FETCH_ACTIVE_USER_SUCCESS = 'FETCH_ACTIVE_USER_SUCCESS'
export const FETCH_ACTIVE_USER_FAILURE = 'FETCH_ACTIVE_USER_FAILURE'

export const CHANGE_USER_PASSWORD = 'CHANGE_USER_PASSWORD'
export const CHANGE_USER_PASSWORD_SUCCESS = 'CHANGE_USER_PASSWORD_SUCCESS'
export const CHANGE_USER_PASSWORD_FAILURE = 'CHANGE_USER_PASSWORD_FAILURE'