export const ATTEMPT_LOGIN = 'ATTEMPT_LOGIN'
export const ATTEMPT_LOGIN_SUCCESS = 'ATTEMPT_LOGIN_SUCCESS'
export const ATTEMPT_LOGIN_FAILURE = 'ATTEMPT_LOGIN_FAILURE'

export const CHECK_SAVED_TOKEN = 'CHECK_SAVED_TOKEN'
export const CHECK_SAVED_TOKEN_SUCCESS = 'CHECK_SAVED_TOKEN_SUCCESS'
export const CHECK_SAVED_TOKEN_FAILURE = 'CHECK_SAVED_TOKEN_FAILURE'

export const DECODE_TOKEN = 'DECODE_TOKEN'
export const DECODE_TOKEN_SUCCESS = 'DECODE_TOKEN_SUCCESS'
export const DECODE_TOKEN_FAILURE = 'DECODE_TOKEN_FAILURE'

export const LOGOUT = 'LOGOUT'
