export const FETCH_COMPANIES = 'FETCH_COMPANIES'
export const FETCH_COMPANIES_SUCCESS = 'FETCH_COMPANIES_SUCCESS'
export const FETCH_COMPANIES_FAILURE = 'FETCH_COMPANIES_FAILURE'

export const FETCH_COMPANIES_FOR_USER = 'FETCH_COMPANIES_FOR_USER'
export const FETCH_COMPANIES_FOR_USER_SUCCESS = 'FETCH_COMPANIES_FOR_USER_SUCCESS'
export const FETCH_COMPANIES_FOR_USER_FAILURE = 'FETCH_COMPANIES_FOR_USER_FAILURE'

export const FETCH_COMPANY_DETAILS = 'FETCH_COMPANY_DETAILS'
export const FETCH_COMPANY_DETAILS_SUCCESS = 'FETCH_COMPANY_DETAILS_SUCCESS'
export const FETCH_COMPANY_DETAILS_FAILURE = 'FETCH_COMPANY_DETAILS_FAILURE'

export const CHANGE_COMPANY_DETAILS = 'CHANGE_COMPANY_DETAILS'
export const CHANGE_COMPANY_DETAILS_SUCCESS = 'CHANGE_COMPANY_DETAILS_SUCCESS'
export const CHANGE_COMPANY_DETAILS_FAILURE = 'CHANGE_COMPANY_DETAILS_FAILURE'

export const CREATE_COMPANY = 'CREATE_COMPANY'
export const CREATE_COMPANY_SUCCESS = 'CREATE_COMPANY_SUCCESS'
export const CREATE_COMPANY_FAILURE = 'CREATE_COMPANY_FAILURE'