export const FETCH_DEADLINE = 'FETCH_DEADLINE'
export const FETCH_DEADLINE_SUCCESS = 'FETCH_DEADLINE_SUCCESS'
export const FETCH_DEADLINE_FAILURE = 'FETCH_DEADLINE_FAILURE'

export const SAVE_DEADLINE = 'SAVE_DEADLINE'
export const SAVE_DEADLINE_SUCCESS = 'SAVE_DEADLINE_SUCCESS'
export const SAVE_DEADLINE_FAILURE = 'SAVE_DEADLINE_FAILURE'

