export const FETCH_EQUIPMENT_LIST = 'FETCH_EQUIPMENT_LIST'
export const FETCH_EQUIPMENT_LIST_SUCCESS = 'FETCH_EQUIPMENT_LIST_SUCCESS'
export const FETCH_EQUIPMENT_LIST_FAILURE = 'FETCH_EQUIPMENT_LIST_FAILURE'

export const FETCH_EQUIPMENT_DETAILS = 'FETCH_EQUIPMENT_DETAILS'
export const FETCH_EQUIPMENT_DETAILS_SUCCESS = 'FETCH_EQUIPMENT_DETAILS_SUCCESS'
export const FETCH_EQUIPMENT_DETAILS_FAILURE = 'FETCH_EQUIPMENT_DETAILS_FAILURE'

export const ADD_EQUIPMENT = 'ADD_EQUIPMENT'
export const ADD_EQUIPMENT_SUCCESS = 'ADD_EQUIPMENT_SUCCESS'
export const ADD_EQUIPMENT_FAILURE = 'ADD_EQUIPMENT_FAILURE'

export const DELETE_EQUIPMENT = 'DELETE_EQUIPMENT'
export const DELETE_EQUIPMENT_SUCCESS = 'DELETE_EQUIPMENT_SUCCESS'
export const DELETE_EQUIPMENT_FAILURE = 'DELETE_EQUIPMENT_FAILURE'

export const SAVE_EQUIPMENT = 'SAVE_EQUIPMENT'
export const SAVE_EQUIPMENT_SUCCESS = 'SAVE_EQUIPMENT_SUCCESS'
export const SAVE_EQUIPMENT_FAILURE = 'SAVE_EQUIPMENT_FAILURE'