export const FETCH_EVENT_CONFIG = 'FETCH_EVENT_CONFIG'
export const FETCH_EVENT_CONFIG_SUCCESS = 'FETCH_EVENT_CONFIG_SUCCESS'
export const FETCH_EVENT_CONFIG_FAILURE = 'FETCH_EVENT_CONFIG_FAILURE'

export const SAVE_EVENT_CONFIG = 'SAVE_EVENT_CONFIG'
export const SAVE_EVENT_CONFIG_SUCCESS = 'SAVE_EVENT_CONFIG_SUCCESS'
export const SAVE_EVENT_CONFIG_FAILURE = 'SAVE_EVENT_CONFIG_FAILURE'

