export const FETCH_GREETING = 'FETCH_GREETING'
export const FETCH_GREETING_SUCCESS = 'FETCH_GREETING_SUCCESS'
export const FETCH_GREETING_FAILURE = 'FETCH_GREETING_FAILURE'

export const CHANGE_LANGUAGE = 'CHANGE_LANGUAGE'

export const CHANGE_THEME = 'CHANGE_THEME'