export const FETCH_SPONSORSHIP_PACKAGES = 'FETCH_SPONSORSHIP_PACKAGES';
export const FETCH_SPONSORSHIP_PACKAGES_SUCCESS = 'FETCH_SPONSORSHIP_PACKAGES_SUCCESS';
export const FETCH_SPONSORSHIP_PACKAGES_FAILURE = 'FETCH_SPONSORSHIP_PACKAGES_FAILURE';

export const FETCH_SPONSORSHIP_PACKAGE_DETAILS = 'FETCH_SPONSORSHIP_PACKAGE_DETAILS';
export const FETCH_SPONSORSHIP_PACKAGE_DETAILS_SUCCESS = 'FETCH_SPONSORSHIP_PACKAGE_DETAILS_SUCCESS';
export const FETCH_SPONSORSHIP_PACKAGE_DETAILS_FAILURE = 'FETCH_SPONSORSHIP_PACKAGE_DETAILS_FAILURE';

export const ADD_SPONSORSHIP_PACKAGE = 'ADD_SPONSORSHIP_PACKAGE';
export const ADD_SPONSORSHIP_PACKAGE_SUCCESS = 'ADD_SPONSORSHIP_PACKAGE_SUCCESS';
export const ADD_SPONSORSHIP_PACKAGE_FAILURE = 'ADD_SPONSORSHIP_PACKAGE_FAILURE';

export const DELETE_SPONSORSHIP_PACKAGE = 'DELETE_SPONSORSHIP_PACKAGE';
export const DELETE_SPONSORSHIP_PACKAGE_SUCCESS = 'DELETE_SPONSORSHIP_PACKAGE_SUCCESS';
export const DELETE_SPONSORSHIP_PACKAGE_FAILURE = 'DELETE_SPONSORSHIP_PACKAGE_FAILURE';

export const SAVE_SPONSORSHIP_PACKAGE = 'SAVE_SPONSORSHIP_PACKAGE';
export const SAVE_SPONSORSHIP_PACKAGE_SUCCESS = 'SAVE_SPONSORSHIP_PACKAGE_SUCCESS';
export const SAVE_SPONSORSHIP_PACKAGE_FAILURE = 'SAVE_SPONSORSHIP_PACKAGE_FAILURE';

export const ADD_EQUIPMENT_TO_SP = 'ADD_EQUIPMENT_TO_SP';
export const ADD_EQUIPMENT_TO_SP_SUCCESS = 'ADD_EQUIPMENT_TO_SP_SUCCESS';
export const ADD_EQUIPMENT_TO_SP_FAILURE = 'ADD_EQUIPMENT_TO_SP_FAILURE';

export const MODIFY_SP_EQUIPMENT = 'MODIFY_SP_EQUIPMENT';
export const MODIFY_SP_EQUIPMENT_SUCCESS = 'MODIFY_SP_EQUIPMENT_SUCCESS';
export const MODIFY_SP_EQUIPMENT_FAILURE = 'MODIFY_SP_EQUIPMENT_FAILURE';

export const DELETE_SP_EQUIPMENT = 'DELETE_SP_EQUIPMENT';
export const DELETE_SP_EQUIPMENT_SUCCESS = 'DELETE_SP_EQUIPMENT_SUCCESS';
export const DELETE_SP_EQUIPMENT_FAILURE = 'DELETE_SP_EQUIPMENT_FAILURE';