export const FETCH_USERS = 'FETCH_USERS'
export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS'
export const FETCH_USERS_FAILURE = 'FETCH_USERS_FAILURE'

export const FETCH_USER_DETAILS = 'FETCH_USER_DETAILS'
export const FETCH_USER_DETAILS_SUCCESS = 'FETCH_USER_DETAILS_SUCCESS'
export const FETCH_USER_DETAILS_FAILURE = 'FETCH_USER_DETAILS_FAILURE'

export const CHANGE_USER_DETAILS = 'CHANGE_USER_DETAILS'
export const CHANGE_USER_DETAILS_SUCCESS = 'CHANGE_USER_DETAILS_SUCCESS'
export const CHANGE_USER_DETAILS_FAILURE = 'CHANGE_USER_DETAILS_FAILURE'

export const DELETE_USER = 'DELETE_USER'
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS'
export const DELETE_USER_FAILURE = 'DELETE_USER_FAILURE'

export const ADD_NEW_USER = 'ADD_NEW_USER'
export const ADD_NEW_USER_SUCCESS = 'ADD_NEW_USER_SUCCESS'
export const ADD_NEW_USER_FAILURE = 'ADD_NEW_USER_FAILURE'